### ISSUE TITLE
it does not work , see pic below

### ISSUE THREAD

**Issue by stickylabdev** [sekheng/SP4_LegendOfZelda#1]
![image](https://user-images.githubusercontent.com/13078369/71009307-94f35f80-211c-11ea-8419-c23258c9e3fc.png)

**Comment by sekheng** [comment]
Yes. It is trying to get the SQLite database it can't find the table in the database obviously. You shouldn't be touching this project

**Comment by stickylabdev** [comment]
ah ok , but i want to make some zelda game

**Comment by stickylabdev** [comment]
bythe way the joystick conttroller aslo did not worked

**Comment by sekheng** [comment]
We just randomly name this project as Zelda and the game we created does not representzelda in any way.Dont use this project as a base

**Comment by stickylabdev** [comment]
:(
